### ISSUE TITLE
小米9后台并没有持续定位

### ISSUE THREAD

**Issue by onlyay** [leielyq/-SDK-demo#1]
最近有一个后天持续定位的需求，本以为找到解决办法了，没想到是我想多了。

**Comment by leielyq** [comment]
哦哦，那你可能没遇到，因为这个我和官方沟通了，他们承认了只要有定位权限就会一直定位。
你可以试着用排除法做SDK的排查，还有也可以试着强制关闭定位权限，看看报错Logcat。如果还找不到，那就需要反编译每个jar包，然后搜索定位相关的代码。
总之，加油啦

**Comment by onlyay** [comment]
谢啦，我最近找了很多关于后台定位的代码，但是都没有成功，我给他们都有留言反馈，但是都石沉大海。您是唯一一个有反馈的，还是谢谢啦。
